'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Localization
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JobMaker.Localization", GetType(Localization).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin.
        '''</summary>
        Friend Shared ReadOnly Property Admin() As String
            Get
                Return ResourceManager.GetString("Admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Админ.
        '''</summary>
        Friend Shared ReadOnly Property AdminRU() As String
            Get
                Return ResourceManager.GetString("AdminRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property AdminTip() As String
            Get
                Return ResourceManager.GetString("AdminTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Какие права нужны для захода на профессию?.
        '''</summary>
        Friend Shared ReadOnly Property AdminTipRU() As String
            Get
                Return ResourceManager.GetString("AdminTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Optional settings.
        '''</summary>
        Friend Shared ReadOnly Property AdvSettings() As String
            Get
                Return ResourceManager.GetString("AdvSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Доп. настройки.
        '''</summary>
        Friend Shared ReadOnly Property AdvSettingsRU() As String
            Get
                Return ResourceManager.GetString("AdvSettingsRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dismiss after death.
        '''</summary>
        Friend Shared ReadOnly Property AfterDeath() As String
            Get
                Return ResourceManager.GetString("AfterDeath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Уволить после смерти.
        '''</summary>
        Friend Shared ReadOnly Property AfterDeathRU() As String
            Get
                Return ResourceManager.GetString("AfterDeathRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arrest baton.
        '''</summary>
        Friend Shared ReadOnly Property ArrestStick() As String
            Get
                Return ResourceManager.GetString("ArrestStick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Палка для ареста.
        '''</summary>
        Friend Shared ReadOnly Property ArrestStickRU() As String
            Get
                Return ResourceManager.GetString("ArrestStickRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Battering ram.
        '''</summary>
        Friend Shared ReadOnly Property BatteringRam() As String
            Get
                Return ResourceManager.GetString("BatteringRam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Таран.
        '''</summary>
        Friend Shared ReadOnly Property BatteringRamRU() As String
            Get
                Return ResourceManager.GetString("BatteringRamRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property CategoryTip() As String
            Get
                Return ResourceManager.GetString("CategoryTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to В какую категорию входит профессия? (Категория должна быть создана в файле categories.lua) Пример: Преступность.
        '''</summary>
        Friend Shared ReadOnly Property CategoryTipRU() As String
            Get
                Return ResourceManager.GetString("CategoryTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is it chief?.
        '''</summary>
        Friend Shared ReadOnly Property Chief() As String
            Get
                Return ResourceManager.GetString("Chief", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Это шеф полиции?.
        '''</summary>
        Friend Shared ReadOnly Property ChiefRU() As String
            Get
                Return ResourceManager.GetString("ChiefRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property ColorTip() As String
            Get
                Return ResourceManager.GetString("ColorTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Какой цвет у профессии? (В формате RGB) Пример: 255,255,255 - черный.
        '''</summary>
        Friend Shared ReadOnly Property ColorTipRU() As String
            Get
                Return ResourceManager.GetString("ColorTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Coming soon....
        '''</summary>
        Friend Shared ReadOnly Property ComingSoon() As String
            Get
                Return ResourceManager.GetString("ComingSoon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Скоро....
        '''</summary>
        Friend Shared ReadOnly Property ComingSoonRU() As String
            Get
                Return ResourceManager.GetString("ComingSoonRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property CommandTip() As String
            Get
                Return ResourceManager.GetString("CommandTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Команда, с помощью которой можно будет перейти на эту профессию. Пример: bandit.
        '''</summary>
        Friend Shared ReadOnly Property CommandTipRU() As String
            Get
                Return ResourceManager.GetString("CommandTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is it cook?.
        '''</summary>
        Friend Shared ReadOnly Property Cook() As String
            Get
                Return ResourceManager.GetString("Cook", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Это повар?.
        '''</summary>
        Friend Shared ReadOnly Property CookRU() As String
            Get
                Return ResourceManager.GetString("CookRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy text.
        '''</summary>
        Friend Shared ReadOnly Property CopyButton() As String
            Get
                Return ResourceManager.GetString("CopyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Скопировать текст.
        '''</summary>
        Friend Shared ReadOnly Property CopyButtonRU() As String
            Get
                Return ResourceManager.GetString("CopyButtonRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULX Team (For Example: VIP).
        '''</summary>
        Friend Shared ReadOnly Property CustomCheck() As String
            Get
                Return ResourceManager.GetString("CustomCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULX Группа (Например: VIP).
        '''</summary>
        Friend Shared ReadOnly Property CustomCheckRU() As String
            Get
                Return ResourceManager.GetString("CustomCheckRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property DescriptionTip() As String
            Get
                Return ResourceManager.GetString("DescriptionTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Краткое описание профессии. Пример: Вы бандит, вы можете отжимать деньги у граждан, и естественно заниматься другой преступной деятельностью..
        '''</summary>
        Friend Shared ReadOnly Property DescriptionTipRU() As String
            Get
                Return ResourceManager.GetString("DescriptionTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate job.
        '''</summary>
        Friend Shared ReadOnly Property Generate() As String
            Get
                Return ResourceManager.GetString("Generate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Сгенерировать профессию.
        '''</summary>
        Friend Shared ReadOnly Property GenerateRU() As String
            Get
                Return ResourceManager.GetString("GenerateRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide job code.
        '''</summary>
        Friend Shared ReadOnly Property Hide() As String
            Get
                Return ResourceManager.GetString("Hide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Скрыть код профессии.
        '''</summary>
        Friend Shared ReadOnly Property HideRU() As String
            Get
                Return ResourceManager.GetString("HideRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is it hobo?.
        '''</summary>
        Friend Shared ReadOnly Property Hobo() As String
            Get
                Return ResourceManager.GetString("Hobo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Это бездомный?.
        '''</summary>
        Friend Shared ReadOnly Property HoboRU() As String
            Get
                Return ResourceManager.GetString("HoboRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Needed permissions.
        '''</summary>
        Friend Shared ReadOnly Property JobAdmin() As String
            Get
                Return ResourceManager.GetString("JobAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Нужные права.
        '''</summary>
        Friend Shared ReadOnly Property JobAdminRU() As String
            Get
                Return ResourceManager.GetString("JobAdminRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job category (DarkRP v2.6.x).
        '''</summary>
        Friend Shared ReadOnly Property JobCategory() As String
            Get
                Return ResourceManager.GetString("JobCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Категория профессии (DarkRP v2.6.x).
        '''</summary>
        Friend Shared ReadOnly Property JobCategoryRU() As String
            Get
                Return ResourceManager.GetString("JobCategoryRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color for a job.
        '''</summary>
        Friend Shared ReadOnly Property JobColor() As String
            Get
                Return ResourceManager.GetString("JobColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Цвет профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobColorRU() As String
            Get
                Return ResourceManager.GetString("JobColorRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command for a job.
        '''</summary>
        Friend Shared ReadOnly Property JobCommand() As String
            Get
                Return ResourceManager.GetString("JobCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Команда для профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobCommandRU() As String
            Get
                Return ResourceManager.GetString("JobCommandRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job description.
        '''</summary>
        Friend Shared ReadOnly Property JobDescription() As String
            Get
                Return ResourceManager.GetString("JobDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Описание профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobDescriptionRU() As String
            Get
                Return ResourceManager.GetString("JobDescriptionRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gun license.
        '''</summary>
        Friend Shared ReadOnly Property JobLicense() As String
            Get
                Return ResourceManager.GetString("JobLicense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Лицензия на оружие.
        '''</summary>
        Friend Shared ReadOnly Property JobLicenseRU() As String
            Get
                Return ResourceManager.GetString("JobLicenseRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum players.
        '''</summary>
        Friend Shared ReadOnly Property JobMax() As String
            Get
                Return ResourceManager.GetString("JobMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Максимум игроков.
        '''</summary>
        Friend Shared ReadOnly Property JobMaxRU() As String
            Get
                Return ResourceManager.GetString("JobMaxRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Models for job.
        '''</summary>
        Friend Shared ReadOnly Property JobModels() As String
            Get
                Return ResourceManager.GetString("JobModels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Модели, которые использует ваша профессия.
        '''</summary>
        Friend Shared ReadOnly Property JobModelsRU() As String
            Get
                Return ResourceManager.GetString("JobModelsRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job name.
        '''</summary>
        Friend Shared ReadOnly Property JobName() As String
            Get
                Return ResourceManager.GetString("JobName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Название вашей профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobNameRU() As String
            Get
                Return ResourceManager.GetString("JobNameRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job salary.
        '''</summary>
        Friend Shared ReadOnly Property JobSalary() As String
            Get
                Return ResourceManager.GetString("JobSalary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Зарплата.
        '''</summary>
        Friend Shared ReadOnly Property JobSalaryRU() As String
            Get
                Return ResourceManager.GetString("JobSalaryRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voting.
        '''</summary>
        Friend Shared ReadOnly Property JobVote() As String
            Get
                Return ResourceManager.GetString("JobVote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Голосование.
        '''</summary>
        Friend Shared ReadOnly Property JobVoteRU() As String
            Get
                Return ResourceManager.GetString("JobVoteRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weapons.
        '''</summary>
        Friend Shared ReadOnly Property JobWeapons() As String
            Get
                Return ResourceManager.GetString("JobWeapons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Оружия.
        '''</summary>
        Friend Shared ReadOnly Property JobWeaponsRU() As String
            Get
                Return ResourceManager.GetString("JobWeaponsRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property LicenseNo() As String
            Get
                Return ResourceManager.GetString("LicenseNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Нет.
        '''</summary>
        Friend Shared ReadOnly Property LicenseNoRU() As String
            Get
                Return ResourceManager.GetString("LicenseNoRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LicenseTip() As String
            Get
                Return ResourceManager.GetString("LicenseTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Есть ли у профессии лицензия на оружие?.
        '''</summary>
        Friend Shared ReadOnly Property LicenseTipRU() As String
            Get
                Return ResourceManager.GetString("LicenseTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property LicenseYes() As String
            Get
                Return ResourceManager.GetString("LicenseYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Есть.
        '''</summary>
        Friend Shared ReadOnly Property LicenseYesRU() As String
            Get
                Return ResourceManager.GetString("LicenseYesRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lockpick.
        '''</summary>
        Friend Shared ReadOnly Property Lockpick() As String
            Get
                Return ResourceManager.GetString("Lockpick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Отмычка.
        '''</summary>
        Friend Shared ReadOnly Property LockpickRU() As String
            Get
                Return ResourceManager.GetString("LockpickRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property MaxTip() As String
            Get
                Return ResourceManager.GetString("MaxTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Максимальное количество игроков, которое может одновременно занимать профессию..
        '''</summary>
        Friend Shared ReadOnly Property MaxTipRU() As String
            Get
                Return ResourceManager.GetString("MaxTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is it mayor?.
        '''</summary>
        Friend Shared ReadOnly Property Mayor() As String
            Get
                Return ResourceManager.GetString("Mayor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Это мэр?.
        '''</summary>
        Friend Shared ReadOnly Property MayorRU() As String
            Get
                Return ResourceManager.GetString("MayorRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is it medic?.
        '''</summary>
        Friend Shared ReadOnly Property Medic() As String
            Get
                Return ResourceManager.GetString("Medic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Это медик?.
        '''</summary>
        Friend Shared ReadOnly Property MedicRU() As String
            Get
                Return ResourceManager.GetString("MedicRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Medic kit.
        '''</summary>
        Friend Shared ReadOnly Property Medkit() As String
            Get
                Return ResourceManager.GetString("Medkit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Набор медика.
        '''</summary>
        Friend Shared ReadOnly Property MedkitRU() As String
            Get
                Return ResourceManager.GetString("MedkitRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property ModelTip() As String
            Get
                Return ResourceManager.GetString("ModelTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Какие игровые модели будет использовать профессия? (В кавычках через запятую) Приммер: &quot;models/player/alyx.mdl&quot;,&quot;models/player/barney.mdl&quot;.
        '''</summary>
        Friend Shared ReadOnly Property ModelTipRU() As String
            Get
                Return ResourceManager.GetString("ModelTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property NameTip() As String
            Get
                Return ResourceManager.GetString("NameTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Название вашей профессии (можно на русском). Пример: Бандит.
        '''</summary>
        Friend Shared ReadOnly Property NameTipRU() As String
            Get
                Return ResourceManager.GetString("NameTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Needed job before changing.
        '''</summary>
        Friend Shared ReadOnly Property NeedChangeFrom() As String
            Get
                Return ResourceManager.GetString("NeedChangeFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Нужная профессия до смены.
        '''</summary>
        Friend Shared ReadOnly Property NeedChangeFromRU() As String
            Get
                Return ResourceManager.GetString("NeedChangeFromRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Generator.
        '''</summary>
        Friend Shared ReadOnly Property ProgramName() As String
            Get
                Return ResourceManager.GetString("ProgramName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Генератор профессий.
        '''</summary>
        Friend Shared ReadOnly Property ProgramNameRU() As String
            Get
                Return ResourceManager.GetString("ProgramNameRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property SalaryTip() As String
            Get
                Return ResourceManager.GetString("SalaryTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Сколько будет зарабатывать игрок на данной профессии? .
        '''</summary>
        Friend Shared ReadOnly Property SalaryTipRU() As String
            Get
                Return ResourceManager.GetString("SalaryTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image source.
        '''</summary>
        Friend Shared ReadOnly Property SourceSite() As String
            Get
                Return ResourceManager.GetString("SourceSite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Картинки взяты отсюда.
        '''</summary>
        Friend Shared ReadOnly Property SourceSiteRU() As String
            Get
                Return ResourceManager.GetString("SourceSiteRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stun Baton.
        '''</summary>
        Friend Shared ReadOnly Property Stunstick() As String
            Get
                Return ResourceManager.GetString("Stunstick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Электродубинка.
        '''</summary>
        Friend Shared ReadOnly Property StunstickRU() As String
            Get
                Return ResourceManager.GetString("StunstickRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Superadmin.
        '''</summary>
        Friend Shared ReadOnly Property SuperAdmin() As String
            Get
                Return ResourceManager.GetString("SuperAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Суперадмин.
        '''</summary>
        Friend Shared ReadOnly Property SuperAdminRU() As String
            Get
                Return ResourceManager.GetString("SuperAdminRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEAM-name for your job.
        '''</summary>
        Friend Shared ReadOnly Property TeamName() As String
            Get
                Return ResourceManager.GetString("TeamName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEAM-Название для вашей профессии.
        '''</summary>
        Friend Shared ReadOnly Property TeamNameRU() As String
            Get
                Return ResourceManager.GetString("TeamNameRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property TeamTip() As String
            Get
                Return ResourceManager.GetString("TeamTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Можно использовать название вашей профессии (на латинице). Пример: TEAM_BANDIT.
        '''</summary>
        Friend Shared ReadOnly Property TeamTipRU() As String
            Get
                Return ResourceManager.GetString("TeamTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unarrest baton.
        '''</summary>
        Friend Shared ReadOnly Property UnArrestStick() As String
            Get
                Return ResourceManager.GetString("UnArrestStick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Палка снятия ареста.
        '''</summary>
        Friend Shared ReadOnly Property UnArrestStickRU() As String
            Get
                Return ResourceManager.GetString("UnArrestStickRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend Shared ReadOnly Property UpdateButton() As String
            Get
                Return ResourceManager.GetString("UpdateButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Начать.
        '''</summary>
        Friend Shared ReadOnly Property UpdateButtonRU() As String
            Get
                Return ResourceManager.GetString("UpdateButtonRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating.
        '''</summary>
        Friend Shared ReadOnly Property UpdateMenu() As String
            Get
                Return ResourceManager.GetString("UpdateMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Обновление.
        '''</summary>
        Friend Shared ReadOnly Property UpdateMenuRU() As String
            Get
                Return ResourceManager.GetString("UpdateMenuRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating starts after pressing the button below..
        '''</summary>
        Friend Shared ReadOnly Property UpdateText() As String
            Get
                Return ResourceManager.GetString("UpdateText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Обновление начнется после нажатия на кнопку ниже..
        '''</summary>
        Friend Shared ReadOnly Property UpdateTextRU() As String
            Get
                Return ResourceManager.GetString("UpdateTextRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend Shared ReadOnly Property User() As String
            Get
                Return ResourceManager.GetString("User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Игрок.
        '''</summary>
        Friend Shared ReadOnly Property UserRU() As String
            Get
                Return ResourceManager.GetString("UserRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property VoteNo() As String
            Get
                Return ResourceManager.GetString("VoteNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Нет.
        '''</summary>
        Friend Shared ReadOnly Property VoteNoRU() As String
            Get
                Return ResourceManager.GetString("VoteNoRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property VoteTip() As String
            Get
                Return ResourceManager.GetString("VoteTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Требуется ли создавать голосование для перехода на профессию?.
        '''</summary>
        Friend Shared ReadOnly Property VoteTipRU() As String
            Get
                Return ResourceManager.GetString("VoteTipRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property VoteYes() As String
            Get
                Return ResourceManager.GetString("VoteYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да.
        '''</summary>
        Friend Shared ReadOnly Property VoteYesRU() As String
            Get
                Return ResourceManager.GetString("VoteYesRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weapon checker.
        '''</summary>
        Friend Shared ReadOnly Property WeaponChecker() As String
            Get
                Return ResourceManager.GetString("WeaponChecker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Обыск.
        '''</summary>
        Friend Shared ReadOnly Property WeaponCheckerRU() As String
            Get
                Return ResourceManager.GetString("WeaponCheckerRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property WeaponTip() As String
            Get
                Return ResourceManager.GetString("WeaponTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to С какими оружиями будет появлятся игрок на данной профессии? (В кавычках через запятую) Пример: &quot;weapon_ak47&quot;, &quot;weapon_ar2&quot;.
        '''</summary>
        Friend Shared ReadOnly Property WeaponTipRU() As String
            Get
                Return ResourceManager.GetString("WeaponTipRU", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
