'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Localization
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JobMaker.Localization", GetType(Localization).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy text.
        '''</summary>
        Friend Shared ReadOnly Property CopyButton() As String
            Get
                Return ResourceManager.GetString("CopyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Скопировать текст.
        '''</summary>
        Friend Shared ReadOnly Property CopyButtonRU() As String
            Get
                Return ResourceManager.GetString("CopyButtonRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate job.
        '''</summary>
        Friend Shared ReadOnly Property Generate() As String
            Get
                Return ResourceManager.GetString("Generate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Сгенерировать профессию.
        '''</summary>
        Friend Shared ReadOnly Property GenerateRU() As String
            Get
                Return ResourceManager.GetString("GenerateRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job category (DarkRP v2.6.x).
        '''</summary>
        Friend Shared ReadOnly Property JobCategory() As String
            Get
                Return ResourceManager.GetString("JobCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Категория профессии (DarkRP v2.6.x).
        '''</summary>
        Friend Shared ReadOnly Property JobCategoryRU() As String
            Get
                Return ResourceManager.GetString("JobCategoryRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color for a job.
        '''</summary>
        Friend Shared ReadOnly Property JobColor() As String
            Get
                Return ResourceManager.GetString("JobColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Цвет профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobColorRU() As String
            Get
                Return ResourceManager.GetString("JobColorRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command for a job.
        '''</summary>
        Friend Shared ReadOnly Property JobCommand() As String
            Get
                Return ResourceManager.GetString("JobCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Команда для профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobCommandRU() As String
            Get
                Return ResourceManager.GetString("JobCommandRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job description.
        '''</summary>
        Friend Shared ReadOnly Property JobDescription() As String
            Get
                Return ResourceManager.GetString("JobDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Описание профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobDescriptionRU() As String
            Get
                Return ResourceManager.GetString("JobDescriptionRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum players.
        '''</summary>
        Friend Shared ReadOnly Property JobMax() As String
            Get
                Return ResourceManager.GetString("JobMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Максимум игроков.
        '''</summary>
        Friend Shared ReadOnly Property JobMaxRU() As String
            Get
                Return ResourceManager.GetString("JobMaxRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Models for job.
        '''</summary>
        Friend Shared ReadOnly Property JobModels() As String
            Get
                Return ResourceManager.GetString("JobModels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Модели, которые использует ваша профессия.
        '''</summary>
        Friend Shared ReadOnly Property JobModelsRU() As String
            Get
                Return ResourceManager.GetString("JobModelsRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job name.
        '''</summary>
        Friend Shared ReadOnly Property JobName() As String
            Get
                Return ResourceManager.GetString("JobName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Название вашей профессии.
        '''</summary>
        Friend Shared ReadOnly Property JobNameRU() As String
            Get
                Return ResourceManager.GetString("JobNameRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job salary.
        '''</summary>
        Friend Shared ReadOnly Property JobSalary() As String
            Get
                Return ResourceManager.GetString("JobSalary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Зарплата.
        '''</summary>
        Friend Shared ReadOnly Property JobSalaryRU() As String
            Get
                Return ResourceManager.GetString("JobSalaryRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voting.
        '''</summary>
        Friend Shared ReadOnly Property JobVote() As String
            Get
                Return ResourceManager.GetString("JobVote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Голосование.
        '''</summary>
        Friend Shared ReadOnly Property JobVoteRU() As String
            Get
                Return ResourceManager.GetString("JobVoteRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weapons.
        '''</summary>
        Friend Shared ReadOnly Property JobWeapons() As String
            Get
                Return ResourceManager.GetString("JobWeapons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Оружия.
        '''</summary>
        Friend Shared ReadOnly Property JobWeaponsRU() As String
            Get
                Return ResourceManager.GetString("JobWeaponsRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Generator.
        '''</summary>
        Friend Shared ReadOnly Property ProgramName() As String
            Get
                Return ResourceManager.GetString("ProgramName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Генератор профессий.
        '''</summary>
        Friend Shared ReadOnly Property ProgramNameRU() As String
            Get
                Return ResourceManager.GetString("ProgramNameRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image source.
        '''</summary>
        Friend Shared ReadOnly Property SourceSite() As String
            Get
                Return ResourceManager.GetString("SourceSite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Картинки взяты отсюда.
        '''</summary>
        Friend Shared ReadOnly Property SourceSiteRU() As String
            Get
                Return ResourceManager.GetString("SourceSiteRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEAM-name for your job.
        '''</summary>
        Friend Shared ReadOnly Property TeamName() As String
            Get
                Return ResourceManager.GetString("TeamName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEAM-Название для вашей профессии.
        '''</summary>
        Friend Shared ReadOnly Property TeamNameRU() As String
            Get
                Return ResourceManager.GetString("TeamNameRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property VoteNo() As String
            Get
                Return ResourceManager.GetString("VoteNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Нет.
        '''</summary>
        Friend Shared ReadOnly Property VoteNoRU() As String
            Get
                Return ResourceManager.GetString("VoteNoRU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property VoteYes() As String
            Get
                Return ResourceManager.GetString("VoteYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да.
        '''</summary>
        Friend Shared ReadOnly Property VoteYesRU() As String
            Get
                Return ResourceManager.GetString("VoteYesRU", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
